POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "user1@user.com",
  "password": "123456"
}


###
GET http://localhost:3000/teste
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlcjFAdXNlci5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzEzMTE3MTgsImV4cCI6MTYzMTMxMTc3OH0.-3b-dLjuKjKUmRQ6EB9esxmzWntRkvJnY4R2S4Q7TFo
